package com.jesusdmedinac.kmp.core.model

import kotlinx.serialization.Serializable

/**
 * Aggregated environment health report generated by the diagnostics engine.
 *
 * @property version KMP Tooling version that generated this report.
 * @property timestamp ISO-8601 timestamp string when the diagnostic was performed.
 * @property overallStatus Computed aggregate health status across all checks.
 * @property checks List of individual check results.
 */
@Serializable
data class DiagnosticReport(
    val version: String,
    val timestamp: String,
    val overallStatus: CheckStatus,
    val checks: List<CheckResult>,
) {
    /**
     * Returns true if there are no critical failures in the report.
     */
    val isHealthy: Boolean get() = overallStatus != CheckStatus.FAILURE
}
